export default {
        backgroundCard: {
            grass: '#60CD8B',
            fire: '#FF9696',
            water: '#96CDFF',
            poison: '#a384e8',
            normal: '#B5B9C4',
            bug: '#8BD674',
            flying: '#C8F5FF',
            electric: '#F2cB55',
            ground: '#F78551',
            fairy: '#f5c4f3',
            fighting: '#d98a68',
            psychic: '#a12f7e',
            rock: '#917a5e',
            steel: '#fff',
            ice: '#48f7ed',
            ghost: '#421c63',
            dragon: '#3d5bad',
        },
  
        boxType: {
            grass: '#046D0E',
            fire: '#FF4949',
            water: '#377EE8',
            poison: '#794FD2',
            normal: '#e6e6e6',
            bug: '#009912',
            flying: '#C8F5FF',
            electric: '#feffab',
            ground: '#ffe1d4',
            fairy: '#c97dc6',
            fighting: '#823311',
            psychic: '#ed87ce',
            rock: '#594b3a',
            steel: '#b0b0b0',
            ice: '#55bdc2',
            ghost: '#ae75e0',
            dragon: '#6b8eed',
        }
}